# Generated by Django 2.2.1 on 2019-05-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190519_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('news', models.ManyToManyField(related_name='news_categories', to='news.News')),
            ],
        ),
    ]
